on:
  push:
    branches:
      - 'main'
    paths-ignore: # Don't forget: when making changes down here, sync them with the .vercelignore file.
      - '.husky/**'
      - '.vscode/**'
      - 'LICENSE'
      - 'README.md'

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3 # https://github.com/actions/setup-node
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2 # https://github.com/pnpm/action-setup
        with:
          version: 8

      - uses: actions/checkout@v4 # https://github.com/actions/checkout

      - run: pnpm i --frozen-lockfile

      - run: pnpm lint

      - run: pnpm build

      - uses: exuanbo/actions-deploy-gist@v1 # https://github.com/exuanbo/actions-deploy-gist
        with:
          token: ${{ secrets.GISTS }}
          gist_id: 8c233a74ac06d1980aadaea5e46833eb
          file_path: build/github-stone-admin-request-code-review-from-squads.js
